# Module 2: Data Wrangling

You need to do data wrangling to deal with inconsistent data. This is where 80% of today’s data scientists and engineers spend their time and it is very important to know how to do it. In this module you are going to deal extensively with operations pertaining to data wrangling.

# Defining High Quality Data

### There are a few criteria that help to qualify data as high quality. They are:


*   Validity: How closely the data meets defined business rules or constraints.  Some common constraints include:
    * Mandatory constraints: Certain columns cannot be empty
    * Data-type constraints: Values in a column must be of a certain data type
    * Range constraints: Minimum and maximum values for numbers or dates
    * Foreign-key constraints: A set of values in a column are defined in the column of another table containing unique values  
    *Unique constraints: A field or fields must be unique in a dataset
 *Accuracy: How closely data conforms to a standard or a true value.
* Completeness: How thorough or comprehensive the data and related measures are known
* Consistency: The equivalency of measures across systems and subjects
* Uniformity: Ensuring that the same units of measure are used in all systems
* Traceability: Being able to find (and access) the source of the data
* Timeliness: How quickly and recently the data has been updated


# Basics of Data Cleaning

In [ ]:
#importing the required libraries.
import pandas as pd
import numpy as np

In [ ]:
value = np.array([1, None, 3, 4])
value

array([1, None, 3, 4], dtype=object)

If I try to perform a sum operation on the above data, I will not be able to do so because of the null value that is there in the data.

In [ ]:
value.sum()

TypeError: ignored

This reflects the fact that addition between integer and None is undefined.

## NaN: Missing numerical data
The other missing data representation, NaN (acronym for Not a Number), is different; it is a special floating-point value recognized by all systems that use the standard IEEE floating-point representation:

In [ ]:
value2 = np.array([1, np.nan, 3, 4]) 
value2.dtype

dtype('float64')

NumPy chose a native floating-point type for this array.

In [ ]:
# Regardless of the operation, the result of arithmetic with NaN will be another NaN:
1 + np.nan

nan

In [ ]:
0 *  np.nan

nan

In [ ]:
# NumPy does provide some special aggregations that will ignore these missing values
np.nansum(value2), np.nanmin(value2), np.nanmax(value2)

(8.0, 1.0, 4.0)

Keep in mind that NaN is specifically a floating-point value; there is no equivalent NaN value for integers, strings, or other types

### NaN and None in Pandas

NaN and None both have their place, and Pandas is built to handle the two of them nearly interchangeably, converting between them where appropriate.

NaN can be used as a numerical value on mathematical operations, while None cannot, its an internal python type.


In [ ]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [ ]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [ ]:
x = pd.Series(range(2), dtype=int)
x[0] = None
x

0    NaN
1    1.0
dtype: float64

## Detecting null values
Pandas data structures have two useful methods for detecting null data: isnull() and notnull(). Either one will return a Boolean mask over the data.

In [ ]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [ ]:
data[data.isnull()]

1     NaN
3    None
dtype: object

The isnull() and notnull() methods produce similar Boolean results for DataFrames.

## Dropping null values
In addition to the masking used before, there are the convenience methods, dropna() (which removes NA values) and fillna() (which fills in NA values). For a Series, the result is straightforward:

In [ ]:
data = data.dropna()
data

0        1
2    hello
dtype: object

In [ ]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df



0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

Note: We cannot drop single values from a DataFrame; we can only drop full rows or full columns. Depending on the application, you might want one or the other, so dropna() gives a number of options for a DataFrame.



In [ ]:
#If you do not pass any parameters then Python drops the rows with Nan.
df.dropna()

0    1  2
1  2.0  3.0  5

In [ ]:
#If you want to drop columns with Nan values, you have to pass the parameter axis.

In [ ]:
df.dropna(axis = "columns")
# df.dropna(axis = 1)

2
0  2
1  5
2  6

## Filling null values

Sometimes rather than dropping NA values, you'd rather replace them with a valid value. This value might be a single number like zero, or it might be some sort of imputation or interpolation from the good values. You could do this in-place using the isnull() method as a mask, but because it is such a common operation Pandas provides the fillna() method, which returns a copy of the array with the null values replaced.

In [ ]:
# Consider the following list
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

If you want to impute the null values with Zeros

In [ ]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

If you want to forward fill

In [ ]:
data.fillna(method = 'ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

If you want to back fill

In [ ]:
data.fillna(method = 'bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

## Using np.where
If you want to do some basic cleaning or feature engineering quickly, np.where, is how you can do it.

Consider if you’re evaluating a column, and you want to know if the age are strictly greater than 18. If they are you want the result to be 'Adult' and if not you want the result to be 'Teen'.


In [ ]:

df2 = pd.DataFrame({'name': ['Michael', 'Ana', 'Sean', 'Carl', 'Bob'], 
                     'second name': ['Hudson', 'Angel', 'Ben', 'Frank', 'Daniel'],
                     'birth place': ['New York', 'New York', 'Los Angeles', 'New York', 'New York'],
                     'age': [15, 35, 56, 18, 28],
                     'number of children': [0, 1, 2, 0, 1]})
df2

name second name  birth place  age  number of children
0  Michael      Hudson     New York   15                   0
1      Ana       Angel     New York   35                   1
2     Sean         Ben  Los Angeles   56                   2
3     Carl       Frank     New York   18                   0
4      Bob      Daniel     New York   28                   1

In [ ]:
df2['Group'] = np.where(df2['age']>18, 'Adult', 'Teen')
df2

name second name  birth place  age  number of children  Group
0  Michael      Hudson     New York   15                   0   Teen
1      Ana       Angel     New York   35                   1  Adult
2     Sean         Ben  Los Angeles   56                   2  Adult
3     Carl       Frank     New York   18                   0   Teen
4      Bob      Daniel     New York   28                   1  Adult

# Data Cleaning with some real time data

### What is our Dataset about?

*Some Background:*

**NYPD Arrests Data (Historic)**


List of every arrest in NYC going back to 2006 through the end of the previous calendar year. This is a breakdown of every arrest effected in NYC by the NYPD going back to 2006 through the end of the previous calendar year. This data is manually extracted every quarter and reviewed by the Office of Management Analysis and Planning before being posted on the NYPD website. Each record represents an arrest effected in NYC by the NYPD and includes information about the type of crime, the location and time of enforcement.
In addition, information related to suspect demographics is also included.
This data can be used by the public to explore the nature of police enforcement activity.

https://data.cityofnewyork.us/Public-Safety/NYPD-Arrests-Data-Historic-/8h9b-rp9u

We shall take a look at a small subset of this data. Lets first import the data in from this URL: https://bit.ly/2Qk25Xx

In [ ]:
import pandas as pd

df1 = pd.read_csv("https://bit.ly/2Qk25Xx")
df1.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


ARREST_KEY ARREST_DATE  PD_CD  ... Y_COORD_CD   Latitude  Longitude
0  173130602  12/31/2017    566  ...     207463  40.735772 -73.715638
1  173114463  12/31/2017    478  ...     219613  40.769437 -73.910241
2  173113513  12/31/2017    849  ...     186857  40.679525 -73.904572
3  173113423  12/31/2017    101  ...     217446  40.763523 -73.987074
4  173113421  12/31/2017    101  ...     216078  40.759768 -73.989811

[5 rows x 18 columns]

In [ ]:
# To see the unique values of any particular column you can use the unique function. 
# Let's look into the unique values of Perpetrator's race.
df1['PERP_RACE'].unique()

array(['BLACK', 'ASIAN / PACIFIC ISLANDER', 'WHITE', 'WHITE HISPANIC',
       'BLACK HISPANIC', 'UNKNOWN', 'AMERICAN INDIAN/ALASKAN NATIVE', nan,
       'WHITE HISPA'], dtype=object)

In [ ]:
#To find the shape of the data.
#This shows the number of rows and columns in the data.
df1.shape

(95967, 18)

**Lets take a look at the column names**

In [ ]:
df1.columns

Index(['ARREST_KEY', 'ARREST_DATE', 'PD_CD', 'PD_DESC', 'KY_CD', 'OFNS_DESC',
       'LAW_CODE', 'LAW_CAT_CD', 'ARREST_BORO', 'ARREST_PRECINCT',
       'JURISDICTION_CODE', 'AGE_GROUP', 'PERP_SEX', 'PERP_RACE', 'X_COORD_CD',
       'Y_COORD_CD', 'Latitude', 'Longitude'],
      dtype='object')

In [ ]:
# Data Type of each column
df1.dtypes

ARREST_KEY            object
ARREST_DATE           object
PD_CD                  int64
PD_DESC               object
KY_CD                float64
OFNS_DESC             object
LAW_CODE              object
LAW_CAT_CD            object
ARREST_BORO           object
ARREST_PRECINCT        int64
JURISDICTION_CODE      int64
AGE_GROUP             object
PERP_SEX              object
PERP_RACE             object
X_COORD_CD             int64
Y_COORD_CD             int64
Latitude             float64
Longitude            float64
dtype: object

In [ ]:
# If you want to check the values of a column
df1['ARREST_PRECINCT'].values

array([105, 114,  73, ...,   7,  14,  30])

In [ ]:
# If you want to change the index of the data to a column
df1.set_index('ARREST_KEY', inplace=True)

# If you run this again you will get an error because Arrest_Key is no longer a part of the columns

In [ ]:
df1

ARREST_DATE  PD_CD  ...   Latitude  Longitude
ARREST_KEY                     ...                      
173130602   12/31/2017    566  ...  40.735772 -73.715638
173114463   12/31/2017    478  ...  40.769437 -73.910241
173113513   12/31/2017    849  ...  40.679525 -73.904572
173113423   12/31/2017    101  ...  40.763523 -73.987074
173113421   12/31/2017    101  ...  40.759768 -73.989811
...                ...    ...  ...        ...        ...
168427638   08/24/2017    114  ...  40.707447 -73.792142
168420087   08/24/2017    101  ...  40.843329 -73.923756
168419787   08/24/2017    258  ...  40.714428 -73.992138
168415098   08/24/2017    244  ...  40.753464 -73.994400
168415095   08/24/2017    922  ...  40.826269 -73.945050

[95967 rows x 17 columns]

## Some Data Exploration

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 95967 entries, 173130602 to 168415095
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   ARREST_DATE        95873 non-null  object 
 1   PD_CD              95967 non-null  int64  
 2   PD_DESC            95672 non-null  object 
 3   KY_CD              95672 non-null  float64
 4   OFNS_DESC          95672 non-null  object 
 5   LAW_CODE           95967 non-null  object 
 6   LAW_CAT_CD         95418 non-null  object 
 7   ARREST_BORO        95967 non-null  object 
 8   ARREST_PRECINCT    95967 non-null  int64  
 9   JURISDICTION_CODE  95967 non-null  int64  
 10  AGE_GROUP          95953 non-null  object 
 11  PERP_SEX           95967 non-null  object 
 12  PERP_RACE          95964 non-null  object 
 13  X_COORD_CD         95967 non-null  int64  
 14  Y_COORD_CD         95967 non-null  int64  
 15  Latitude           95966 non-null  float64
 16  Longitude      

In [ ]:
df1.describe()

PD_CD         KY_CD  ...      Latitude     Longitude
count  95967.000000  95672.000000  ...  95966.000000  95966.000000
mean     480.963394    271.927074  ...     40.739430    -73.925361
std      269.348625    147.190795  ...      0.081517      0.075420
min        0.000000    101.000000  ...     40.500391    -74.251150
25%      259.000000    119.000000  ...     40.677836    -73.976336
50%      478.000000    341.000000  ...     40.737203    -73.929617
75%      729.000000    346.000000  ...     40.813947    -73.883884
max      997.000000    995.000000  ...     40.912476    -73.701906

[8 rows x 8 columns]

Our data has been quickly assessed, and we have got quite some information from this.

## Dropping unneccessary columns

There are some redundant columns in our dataset which will be seldom used. The X_COORD_CD and the Y_COORD_CD might not be used in our analysis. So we can drop these columns from our data.

In [ ]:
columns = df1.columns
columns

Index(['ARREST_DATE', 'PD_CD', 'PD_DESC', 'KY_CD', 'OFNS_DESC', 'LAW_CODE',
       'LAW_CAT_CD', 'ARREST_BORO', 'ARREST_PRECINCT', 'JURISDICTION_CODE',
       'AGE_GROUP', 'PERP_SEX', 'PERP_RACE', 'X_COORD_CD', 'Y_COORD_CD',
       'Latitude', 'Longitude'],
      dtype='object')

In [ ]:
# Let's first create a list comprehension for columns to be dropped.
drop_cols = [columns[i] for i in [13,14]]
df1.drop(drop_cols,axis = 1, inplace = True)
df1

ARREST_DATE  PD_CD  ...   Latitude  Longitude
ARREST_KEY                     ...                      
173130602   12/31/2017    566  ...  40.735772 -73.715638
173114463   12/31/2017    478  ...  40.769437 -73.910241
173113513   12/31/2017    849  ...  40.679525 -73.904572
173113423   12/31/2017    101  ...  40.763523 -73.987074
173113421   12/31/2017    101  ...  40.759768 -73.989811
...                ...    ...  ...        ...        ...
168427638   08/24/2017    114  ...  40.707447 -73.792142
168420087   08/24/2017    101  ...  40.843329 -73.923756
168419787   08/24/2017    258  ...  40.714428 -73.992138
168415098   08/24/2017    244  ...  40.753464 -73.994400
168415095   08/24/2017    922  ...  40.826269 -73.945050

[95967 rows x 15 columns]

### **Note: Inplace = True**
The inplace=True has been added so you don’t need to save over the original df by assigning the result of .drop() to df. Many of the methods in pandas support inplace=True, so try to use it as much as possible to avoid unnecessary reassignment.

## Let's check if there are any missing values in the columns

In [ ]:
df1.isna().sum()

ARREST_DATE           94
PD_CD                  0
PD_DESC              295
KY_CD                295
OFNS_DESC            295
LAW_CODE               0
LAW_CAT_CD           549
ARREST_BORO            0
ARREST_PRECINCT        0
JURISDICTION_CODE      0
AGE_GROUP             14
PERP_SEX               0
PERP_RACE              3
Latitude               1
Longitude              1
dtype: int64

## Handling the missing valus

1. Drop the missings?
2. Impute the missings?

We will drop the columns that have more than 90% NaNs. 
To do this we will use a parameter thresh. You can change the threshold according to your business and data.

In [ ]:
df1.dropna(thresh = int(df1.shape[0]*0.9), axis = 1)

ARREST_DATE  PD_CD  ...   Latitude  Longitude
ARREST_KEY                     ...                      
173130602   12/31/2017    566  ...  40.735772 -73.715638
173114463   12/31/2017    478  ...  40.769437 -73.910241
173113513   12/31/2017    849  ...  40.679525 -73.904572
173113423   12/31/2017    101  ...  40.763523 -73.987074
173113421   12/31/2017    101  ...  40.759768 -73.989811
...                ...    ...  ...        ...        ...
168427638   08/24/2017    114  ...  40.707447 -73.792142
168420087   08/24/2017    101  ...  40.843329 -73.923756
168419787   08/24/2017    258  ...  40.714428 -73.992138
168415098   08/24/2017    244  ...  40.753464 -73.994400
168415095   08/24/2017    922  ...  40.826269 -73.945050

[95967 rows x 15 columns]

## Exercise: 1

### Create a new column called 'JAIL_TIME' from the NYPD dataset.

Use the following rules to form the column:
*    Felony is 3 years
*   Misdemeanors is 12 months
* Violation is 1 month

# Data Preprocessing

Along with cleaning the data, you’ll also need to prepare the data so it is in a form you can use for further analytics.

In [ ]:
# Import the required libraries
import numpy as np
from sklearn import preprocessing

# Let's create a random array of ints to process
ary_int = np.random.randint(-100, 100, 10)
print(ary_int)

# And some str to work with
ary_str = ['foo', 'bar', 'baz', 'x', 'y', 'z']
print(ary_str)

[ 74  79 -77  94  42 -10   0  54 -60  75]
['foo', 'bar', 'baz', 'x', 'y', 'z']


### Label Encoding

**Lets use LabelEncoder on our ary_str.**

Label Encoding is important since certain analytical models cannot directly work on strings. For example: Machine Learning Models. 

We’ll encode labels to each of the strings, with value between 0 and n. In our ary_str, we have 6 unique values so our range would be 0 - 5.

In [ ]:
# Import the required library
from sklearn.preprocessing import LabelEncoder

# Initialize a label encoder
l_encoder = preprocessing.LabelEncoder()
l_encoder.fit(ary_str)

LabelEncoder()

In [ ]:
# Let's check the values after encoding
print(l_encoder.transform(['foo']))
print(l_encoder.transform(['bar']))
print(l_encoder.transform(['baz']))
print(l_encoder.transform(['x']))

[2]
[0]
[1]
[3]


'foo' is assigned 2

'bar' is assigned 0

'baz' is assigned 1

'x' is assigned 3

If you notice closely you can see that the assignment is not ordered of how the strings appear in the array. Though 'foo' comes before 'bar' the encoded value is not in that manner. If you want to get the encoded values in order we can use a different method:

In [ ]:
print(list(l_encoder.classes_))

['bar', 'baz', 'foo', 'x', 'y', 'z']


In [ ]:
print(dict(zip(l_encoder.classes_, l_encoder.transform(l_encoder.classes_))))

{'bar': 0, 'baz': 1, 'foo': 2, 'x': 3, 'y': 4, 'z': 5}


Label encoders can also be applied in dataframes to label multiple columns at the same time

In [ ]:
import pandas as pd
df = pd.DataFrame(data = {'col1': ['foo','bar','foo','bar'],
                          'col2': ['x', 'y', 'x', 'z'], 
                          'col3': [1, 2, 3, 4]})
df

col1 col2  col3
0  foo    x     1
1  bar    y     2
2  foo    x     3
3  bar    z     4

In [ ]:
#using label encoder for this small dataframe
df.apply(l_encoder.fit_transform)

col1  col2  col3
0     1     0     0
1     0     1     1
2     1     0     2
3     0     2     3

### One Hot Encoding

The classic one hot or ‘dummy’ encoding, where single features of categories are then expressed as additional columns of 0s or 1s, depending on it the value appears or not. This process creates a binary column for each category and returns a sparse matrix or dense array.

![alt text](https://cdn-images-1.medium.com/max/1600/1*WXpoiS7HXRC-uwJPYsy1Dg.png)

This type of encoding is needed for feeding categorical data to many scikit models such as linear regression models and SVMs.

Let's use One Hot Encoding for a dataframe

In [ ]:
df

col1 col2  col3
0  foo    x     1
1  bar    y     2
2  foo    x     3
3  bar    z     4

In [ ]:
pd.get_dummies(df)

col3  col1_bar  col1_foo  col2_x  col2_y  col2_z
0     1         0         1       1       0       0
1     2         1         0       0       1       0
2     3         0         1       1       0       0
3     4         1         0       0       0       1

If you notice col3 has numeric values and therefore it has not been encoded. Only the categorical variables have been encoded.


### MinMaxScaler


What about when our features need to be transformed within a certain range. By using MinMaxScaler, each feature can be individually scaled such that it is in the given range. By default the values are between 0 and 1, but you’re able to change the range.

In [ ]:
ary_int

array([ 74,  79, -77,  94,  42, -10,   0,  54, -60,  75])

In [ ]:
from sklearn.preprocessing import MinMaxScaler
mm_scaler = MinMaxScaler(feature_range=(0, 1)) # Between 0 and 1
mm_scaler.fit([ary_int])

print(mm_scaler.data_max_)

print(mm_scaler.fit_transform([ary_int])) #Do you see anythinh wrong with this?

[ 74.  79. -77.  94.  42. -10.   0.  54. -60.  75.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


If you notice the output is all zeros … which is not what we wanted. 
The array is formatted incorrectly.

Scaler returns zeros when we used a shape a numpy array as list, i.e. [1, n]. like above.

Change the shape of array to [n, 1].  and it should work

e.g
mm_scaler = [[15], 
        [48], 
        [23]], 
        ....
        [43]
        
The easiest way to do this is make sure your array is a numpy array, so you’re able to manipulate the shape.

In [ ]:
# Create numpy array
ary_int = np.array([  5, -41, -67,  23, -53, -57, -36, -25,  10,  17])
# Transform
print(mm_scaler.fit_transform(ary_int[:, np.newaxis]))

[[0.8       ]
 [0.28888889]
 [0.        ]
 [1.        ]
 [0.15555556]
 [0.11111111]
 [0.34444444]
 [0.46666667]
 [0.85555556]
 [0.93333333]]


If you want to scale to a larger size.

In [ ]:
mm_scaler = MinMaxScaler(feature_range=(0, 10))
mm_scaler.fit_transform(ary_int.reshape(-1, 1))

array([[ 8.        ],
       [ 2.88888889],
       [ 0.        ],
       [10.        ],
       [ 1.55555556],
       [ 1.11111111],
       [ 3.44444444],
       [ 4.66666667],
       [ 8.55555556],
       [ 9.33333333]])

### Binarizer


You will still get 0s and 1s through this but now they are defined on your own terms. This is the process of ‘thresholding’ numerical features to get boolean values. The values threshold greater than the threshold will map to 1, while those ≤ to will map to 0. As well, this is a common process when text preprocessing to get the term frequencies within a document or corpus.

In [ ]:
ary_int

array([  5, -41, -67,  23, -53, -57, -36, -25,  10,  17])

In [ ]:
from sklearn.preprocessing import Binarizer
# Set -25 as our threshold
tz = Binarizer(threshold=-25.0).fit([ary_int])

tz.transform([ary_int])

array([[1, 0, 0, 1, 0, 0, 0, 0, 1, 1]])

Anything greater than -25 is assigned a 1 and anything below or equl to -25 is assigned a 0.

## Indexing and Slicing of Data

In [5]:
# Lets define our data
pop_dict = {'Singapore': 5.3, 
            'Indonesia': 11.3, 
            'Italy': 15.3, 
            'United Kingdom': 64.9, 
            'Netherlands': 16.9}
population = pd.Series(pop_dict)

data = {'country': ['SG', 'FR', 'GER'],
        'population': [5.6, 64.3, 81.3],
        'area': [30510, 671308, 357050],
        'capital': ['Singapore', 'Paris', 'Berlin']}
countries = pd.DataFrame(data)
countries

country  population    area    capital
0      SG         5.6   30510  Singapore
1      FR        64.3  671308      Paris
2     GER        81.3  357050     Berlin

In [ ]:
#Quick Review of how to get a single column
countries['area']

0     30510
1    671308
2    357050
Name: area, dtype: int64

In [ ]:
#To extract two columns from the DataFrame
countries[['area','population']]

area  population
0   30510         5.6
1  671308        64.3
2  357050        81.3

Notice there are two square brackets!
The outer square bracket denotes the dataframe and the inner square bracket is for the list.

Slicing of data is done using the index in the data and by default it slices the data from rows.

In [ ]:
countries[0:2]

country  population    area    capital
0      SG         5.6   30510  Singapore
1      FR        64.3  671308      Paris

If you want to change the index of this data to countries, you can also slice this according to the new index. Let's do so:

In [ ]:
countries = countries.set_index('country')
countries

population    area    capital
country                               
SG              5.6   30510  Singapore
FR             64.3  671308      Paris
GER            81.3  357050     Berlin

In [ ]:
countries['SG': 'FR']

population    area    capital
country                               
SG              5.6   30510  Singapore
FR             64.3  671308      Paris

### Concept of loc and iloc

By using the square brackets for slicing, you can either slice the data by row or by column but not both together. Pandas provide the option of some advanced indexing using loc and iloc.

**loc: selection by label, <br>
iloc: selection by position**

#### loc

In [ ]:
countries

population    area    capital
country                               
SG              5.6   30510  Singapore
FR             64.3  671308      Paris
GER            81.3  357050     Berlin

In [ ]:
# To select a single element, say I want to select area of Germany.
# The way to pass the labels is df.loc['Row','Column']. you can't do it the other way like df.loc['Column','Row']

countries.loc['GER', 'area']

357050

In [ ]:
# This is not confined to only single values, you can pass a list or pass a sliced data also
countries.loc['FR': 'GER',['area', 'population']]

area  population
country                    
FR       671308        64.3
GER      357050        81.3

#### iloc

In [6]:
# You can get the above output using iloc as well. Let's see how
countries.iloc[0:2, 1:3 ]

population    area
0         5.6   30510
1        64.3  671308

In [7]:
countries

country  population    area    capital
0      SG         5.6   30510  Singapore
1      FR        64.3  671308      Paris
2     GER        81.3  357050     Berlin

Using the iloc you can also select the absolute coordinates/position in the dataframe.

In [8]:
# If you want to see the values of 1st row of the data
countries.iloc[1]

country           FR
population      64.3
area          671308
capital        Paris
Name: 1, dtype: object

In [9]:
countries.iloc[0,0]

'SG'

### So what is the difference that you notice between loc and iloc?

### Exercise: 2

1) To the countries dataframe defined above, create a new column to the data called 'year' and assign value as '2020'.

2) Extract all the data from the dataframe that has area more than 10000.

## Group By


A groupby operation involves some combination of splitting the object, applying a function, and combining the results.
It is similar to SQL GROUP BY or Pivot table in Excel.

In [ ]:
# Lets define a sample dataframe

df = pd.DataFrame({'key':['A','B','C','A','B','C','A','B','C'],
                   'value': [0, 5, 10, 5, 10, 15, 10, 15, 20]})
df

key  value
0   A      0
1   B      5
2   C     10
3   A      5
4   B     10
5   C     15
6   A     10
7   B     15
8   C     20

In [ ]:
# If you want to group by Key then all the uniques key will be grouped and you will get an aggregated value
df.groupby('key').sum()

value
key       
A       15
B       30
C       45

In [ ]:
# You can also aggregate the keys based on their average value
df.groupby('key').mean()

value
key       
A        5
B       10
C       15

### Exercise: 3

Using the CSV from the following URL: http://bit.ly/wkspdata, answer the questions that follow:

1. Using groupby() calculate the average age for each sex.

2. Calculate the average survival ratio for all passengers.

3. Calculate the survival ratio of passengers less than 30 years age.

## Some more Pandas Operations

If you want to extract data satisying a predefined condition, you can use the isin function.

In [ ]:
# Continuing with the above data, if you want to extract all the female passengers from the data.

df[df['sex'].isin(['female'])]

survived  pclass  ... cabin embarked
1           1       1  ...   C85        C
2           1       3  ...   NaN        S
3           1       1  ...  C123        S
8           1       3  ...   NaN        S
9           1       2  ...   NaN        C
..        ...     ...  ...   ...      ...
880         1       2  ...   NaN        S
882         0       3  ...   NaN        S
885         0       3  ...   NaN        Q
887         1       1  ...   B42        S
888         0       3  ...   NaN        S

[314 rows x 11 columns]

You can also use conjunction condition in pandas. 

In [ ]:
# Let's extract all the females less than 30 years age

df[(df['sex']== 'female') & (df['age']>30)]

survived  pclass  ... cabin embarked
1           1       1  ...   C85        C
3           1       1  ...  C123        S
11          1       1  ...  C103        S
15          1       2  ...   NaN        S
18          0       3  ...   NaN        S
..        ...     ...  ...   ...      ...
862         1       1  ...   D17        S
865         1       2  ...   NaN        S
871         1       1  ...   D35        S
879         1       1  ...   C50        C
885         0       3  ...   NaN        Q

[103 rows x 11 columns]

### Exercise: 4

Extract all the passengers who either travelled in 1st Class or had a fare price higher than 70.

You can also check certain textual content in a column.
If you want to extract all the passengers with 'Miss' in their names.

In [ ]:
df[df['name'].str.contains('Miss')]

survived  pclass  ... cabin embarked
2           1       3  ...   NaN        S
10          1       3  ...    G6        S
11          1       1  ...  C103        S
14          0       3  ...   NaN        S
22          1       3  ...   NaN        Q
..        ...     ...  ...   ...      ...
866         1       2  ...   NaN        C
875         1       3  ...   NaN        C
882         0       3  ...   NaN        S
887         1       1  ...   B42        S
888         0       3  ...   NaN        S

[182 rows x 11 columns]

## Modifying Dataframes

In [ ]:
# Let's modify the age of the third record to 25 instead of 26.
df.at[2,'age'] = 25

In [ ]:
df.head()

survived  pclass  ... cabin embarked
0         0       3  ...   NaN        S
1         1       1  ...   C85        C
2         1       3  ...   NaN        S
3         1       1  ...  C123        S
4         0       3  ...   NaN        S

[5 rows x 11 columns]

In [ ]:
#Similarly you can use the indexing option to change it back to 25 again.
df.iat[2,4] = 26

In [ ]:
df.head()

survived  pclass  ... cabin embarked
0         0       3  ...   NaN        S
1         1       1  ...   C85        C
2         1       3  ...   NaN        S
3         1       1  ...  C123        S
4         0       3  ...   NaN        S

[5 rows x 11 columns]

### Removing Missing values

If you want to remove rows with all the columns having missing values you can do it using a 'how' parameter in dropna function.

In [ ]:
#df.dropna(how = 'any') #This will drop any record that has nan value.
df.dropna(how = 'all')

survived  pclass  ... cabin embarked
0           0       3  ...   NaN        S
1           1       1  ...   C85        C
2           1       3  ...   NaN        S
3           1       1  ...  C123        S
4           0       3  ...   NaN        S
..        ...     ...  ...   ...      ...
886         0       2  ...   NaN        S
887         1       1  ...   B42        S
888         0       3  ...   NaN        S
889         1       1  ...  C148        C
890         0       3  ...   NaN        Q

[891 rows x 11 columns]

## Exercise: 5

1. Load the data from the url: "https://bit.ly/2FlFIPH"

2. Check for null values if any.

3. Drop the columns 'fuelsystem' and 'boreratio'.

4. Extract the data only for fuel type gas with four doors in a new dataframe named data_fuel.

5. Use Label Encoding and store the data in data_lab.

6. Use One Hot Encoding and store the data in data_ohe.

7. Change the indexing of the data to car_id.

## Data Cleaning for Strings (Extra)

The beautifier package is able to help you clean up some commonly used patterns for emails or URLs. It’s nothing fancy but can quickly help with clean up.

In [ ]:
# Firstly, install the package
!pip install beautifier

In [2]:
# Import the required library
from beautifier import Email, Url
email_string = 'john@xaltius.tech'
email = Email(email_string)
print(email.domain)
print(email.username)
print(email.is_free_email)

xaltius.tech
john
False


In [ ]:
url_string = 'https://www.economist.com/asia/2019/05/23/narendra-modi-scores-a-remarkable-election-victory'
url = Url(url_string)
print(url.param)
print(url.username)
print(url.domain)

None
{'msg': 'feature is currently available only with linkedin urls'}
economist.com


### **String Matching with fuzzywuzzy**

Uses something called **Levenshtein distance** when comparing. This is a string similarity metric for two sequences, such that the distance between is the number of single character edits required to change one word to the other word.s

A more scientific way of matching words


E.g. if you want to change the string foo into bar, the minimum number of characters to change would be 3, and this is used to determine the ‘distance’.


Let’s see how this works!

*The fuzzywuzzy package has different ways to evaluate strings (WRatio , UQRatio, etc.)*

In [ ]:
!pip3 install fuzzywuzzy

from fuzzywuzzy import fuzz
from fuzzywuzzy import process
foo = 'is this string'
bar = 'like that string?'

/usr/local/lib/python3.6/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [ ]:
#Gives the matching ratio between two strings
print(fuzz.ratio(foo, bar)) 

71


**Tokenized string**

This returns a measure of the sequences’ similarity between 0 and 100 but sorting the token before comparing. This is key as you might just want to see the contents of the strings, rather than their positions.

The strings text1 and text2 have the same tokens but are structurally different. Do you want to treat them the same? Now you can easily look and account for this type of difference within your data.


In [ ]:
text1 = "this is text 1"
text2 = "1 text is this"

In [ ]:
print(fuzz.WRatio(text1,text2))
print(fuzz.token_set_ratio(text1,text2))

95
100


### Matching Closest String from a list

Have you ever encountered a situation like this? <br/>

Me: Did you read that harry potter book? With the name… uum... something title… it has … I dunno.

Friend B: Which Title?? What are you talking about??

Me: umm fire something...

Let's use Fuzzywuzzy to do the following!

Since my guess is ‘fire’ and let’s see how it scores against the possible list of titles.

In [ ]:
my_list = ['Harry Potter and the Philosopher\'s Stone',
'Harry Potter and the Chamber of Secrets',
'Harry Potter and the Prisoner of Azkaban',
'Harry Potter and the Goblet of Fire',
'Harry Potter and the Order of the Phoenix',
'Harry Potter and the Half-Blood Prince',
'Harry Potter and the Deathly Hallows']

In [ ]:
#Top 3 matches from the list
print(process.extract("fire", my_list, limit = 3))

[('Harry Potter and the Goblet of Fire', 60), ('Harry Potter and the Chamber of Secrets', 30), ('Harry Potter and the Half-Blood Prince', 30)]


In [ ]:
results = process.extract("fire", my_list, limit=3)
results

[('Harry Potter and the Goblet of Fire', 60),
 ('Harry Potter and the Chamber of Secrets', 30),
 ('Harry Potter and the Half-Blood Prince', 30)]

In [ ]:
for result in results:
  print('{}: has a score of {}'.format(result[0], result[1]))

Harry Potter and the Goblet of Fire: has a score of 60
Harry Potter and the Chamber of Secrets: has a score of 30
Harry Potter and the Half-Blood Prince: has a score of 30
